name: Push and Pull

on:
  push:
    branches: [ "main", "develop", "feature"]
  pull_request:
    branches: [ "main" , "develop"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

  
